### ISSUE TITLE
Auto build ignored

### ISSUE THREAD

**Issue by pgwilliams** [FHIR/auto-ig-builder#11]
Hi there.   I wired up https://github.com/IHTSDO/snomed-ig to the autobuilder (I hope) as instructed and the webhook seemed to go through OK.   The request was:

```Request URL: https://us-central1-fhir-org-starter-project.cloudfunctions.net/ig-commit-trigger
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/6c8e069
X-GitHub-Delivery: 09035010-d0b9-11e9-93e9-70c19722e856
```
and I got an HTTP 200 back:
```Headers
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Method: POST, OPTIONS
Access-Control-Allow-Origin: *
Content-Length: 53
Content-Type: application/json; charset=utf-8
Date: Fri, 06 Sep 2019 15:14:35 GMT
Function-Execution-Id: gowwl9mp7jmf
Body
{"org":"IHTSDO","repo":"snomed-ig","branch":"master"}
```

But no notification appeared in Zulip and I can't see "ihtsdo" as a folder when I browse to https://build.fhir.org/ig/

Can any further investigation be done from my end?  I did already try the "redeliver" button. 
 Thanks!

**Comment by grahamegrieve** [comment]
how long does the IG take to build?

**Comment by pgwilliams** [comment]
20 seconds.  Here's the log files produced when I run it locally: https://gist.github.com/pgwilliams/4a12333607f6ca55ed18bb51eefa20ff

Thanks @grahamegrieve !

**Comment by jmandel** [comment]
I think the issue is:

https://github.com/IHTSDO/snomed-ig/blob/master/ig.json#L7
"paths": {
"output": "docs",
The expectation is that "output" will be "output" (not "docs"). See
"Control File" documentation at
https://wiki.hl7.org/IG_Publisher_Documentation for full details:

>  "output" : "[output]", // optional; default = "output" (and must be
output for auto-build)

Best,
Josh

**Comment by jmandel** [comment]
(And FYI, I just added
https://github.com/FHIR/auto-ig-builder/commit/148d95feaf319feeb41c2a710d7b60934b800993
as
documentation of this gotcha.)

**Comment by pgwilliams** [comment]
That's coming through great now, thank you!   Closing issue.

https://build.fhir.org/ig/IHTSDO/snomed-ig/
