### ISSUE TITLE
Performance issues on WSL

### ISSUE THREAD

**Issue by LodewijkSioen** [FHIR/auto-ig-builder#31]
I'm using `ig-publisher-base` locally on a windows machine with Docker running on the [WSL](https://learn.microsoft.com/en-us/windows/wsl/) engine. A full publish takes more than 20 minutes. This is because there are serious performance issues in the interop between mounted windows filesystem and the Linux filesystem.

[Microsoft's guidance](https://learn.microsoft.com/en-us/windows/wsl/filesystems#file-storage-and-performance-across-file-systems) is to copy the files you want to work on over to the container filesystem.
I already did this on my own dockerfile and it reduced the build time from 20 minutes to 30 seconds.

If you're open to this, I can create a PR to contribute.

**Comment by jmandel** [comment]
Hmm. Thanks for this report! I wonder if we want to support this as a separate image or set this as an optional behavior, since the common pattern on linux would be to mount a host directory into the container directly, and this image is geared toward such usage (e.g., matching uids on startup).

**Comment by jmandel** [comment]
Looking at the guidance you cited:

>For example, when storing your WSL project files:

>Use the Linux file system root directory: \\wsl$\Ubuntu\home\<user name>\Project
>Not the Windows file system root directory: /mnt/c/Users/<user name>/Project$ or C:\Users\<user name>\Project

... I assume you were already following this advice and *still* seeing long build times?

**Comment by LodewijkSioen** [comment]
Sadly that advise cannot be followed when using WSL as the engine for Docker. I can script around it, but I would prefer not to because it would quite complicate things. I can fire up a PR and then you can comment on it.
