### ISSUE TITLE
Query - is branch aware building possible?

### ISSUE THREAD

**Issue by robeastwood-agency** [FHIR/auto-ig-builder#7]
Hello, firstly let me say how useful and easy to use this tool is. Thank you.

I have a query regarding git branching workflow and am wondering if the build process can build the content of a branch other than the master branch. To make this clearer, I'll explain our workflow.

We are contributing to the [HL7 Australia base profile repository](https://github.com/hl7au/au-fhir-base) via a fork / pull request methodology. Our team members each have a fork of this repository to which we push our proposed changes within a specific feature branch. For example, I have just pushed a minor change into a [branch "observation-age-examples" within my forked copy](https://github.com/robeastwood-agency/au-fhir-base/tree/observation-age-examples). Once I have completed the desired changes within this branch, our process is to have this content peer-reviewed by a team member and once passed, the pull request will be submitted. And in order to facilitate this peer-review, a rendered build and QA report are included in the review (along with direct xml examination etc). Currently for the reviewer to get the build, they need to clone my fork, checkout the branch and do a local build with the IG publisher. This becomes onerous when there are multiple branches from multiple forks to review.

So, that led me to wonder if this server-side auto build process can be branch aware. So that a commit to a given branch other than master would invoke a publication build and this build would use the content of the feature branch rather than the master branch. That way, I could point my reviewer to this build and they could examine the rendered content specific to my branch additions.

I gave this a try to test for myself and found that a commit in my feature branch above, when pushed to my fork with the hook set up, does invoke the trigger to have a build performed. However, the additional content within the branch is not included as it looks to use whatever is the content of the master branch. From the docs I couldn't tell if there was any way to build from a given branch other than master, or if it was even possible. I suspect though that it is not possible as currently configured. If not, is this a feature that could be considered? 

Apologies for the long-winded description which hopefully makes sense. I am happy to provide any other details as needed. 

Thank you
Rob

**Comment by jmandel** [comment]
Thanks Rob! We don't currently build/host branches on IGs, although we have a feature in place to host branches on the main FHIR build (https://github.com/hl7-fhir/auto-ig-builder/commit/626ca7cd5214aa38fb82d616ec6e4a02e85bda2f).

It would be good to do something similar with IGs. Let me do a quick assessment to determine the level of effort for this -- but I think it should be pretty straightforward.

**Comment by jmandel** [comment]
Reading through your write-up in more detail: making this work from forks is a bit tricker than making it run from separate branches within your main repo. Just to understand the use case: how tied are you to using GH forks?

**Comment by jmandel** [comment]
The key question is where the output will be hosted for review. If we restricted auto-build to branches in the "main" repo, we could have URLs like:

https://build.fhir.org/ig/branches/:org/:repo/:branchname

... but if we auto-build forks, this would break down because multiple forks could use the same branch name, and would be competing for the same space on build.fhir.org.

On the other hand, if we asked fork authors to explicitly, independently set up their forks to auto-build, then we'd have URLs like:

https://build.fhir.org/ig/branches/:orgForForkingUser/:repoForForkingUser/:branchname

... which is more work for contributors, but avoids the ambiguity. Thoughts?

**Comment by jmandel** [comment]
Just a quick follow-up that this has been in place for a while now. You can navigate to your IG + `/branches` to see built content across branches.
